### ISSUE TITLE
Week1-Assignment

### ISSUE THREAD

**Issue by Tamara729** [Tamara729/Data-Carpentry#1]
- [✔️] Read GitHub link
- [✔️  Set up 'Command Prompt'
- [✔️] Set up a new repo
- [     ] Email Zack the link to this repo
- [✔️] Upload a data file (.csv)
- [     ] Tag Zack with a message
- [     ] Close issue

**Comment by Tamara729** [comment]
@brymz Everything is working well! 👍

**Comment by brymz** [comment]
@Tamara729 rocking and rolling!
