### ISSUE TITLE
Week 5 - Data Management - Grouping

### ISSUE THREAD

**Issue by Tamara729** [Tamara729/Data-Carpentry#5]
- [✔️] Reading
- [✔️] Group data by treatments (group_by)
- [✔️] Produce a summary table of treatment results (summarize) by making an average (mean) and standard deviation (sd).

**Comment by Tamara729** [comment]
@brymz 

Hi Zack, While reviewing the Wife Harvest data I realized I typed the text "NA" into cells that were purposefully missing data instead of leaving it blank. Does the function na.rm remove this type of NA too, or just the blank cells? 

Thanks,
Tamara 


**R Code**

rm(list=ls())
setwd("T:/Agronomy/7.Hemp/HempExperiements/NutritionStudy_2021/EO_block10/Completed_data_entry")


library(tidyverse)

harvest_data<-read.csv("EO_Harvest_Wife_2021.csv") %>%
  select( Unit, Treatment, Rep, TotalDryWeight_g) %>%
  group_by(Unit,Treatment) %>%
  summarize (avg_yield = mean (TotalDryWeight_g, na.rm = TRUE), SD = sd (TotalDryWeight_g, na.rm = TRUE))

**Comment by brymz** [comment]
Hi @Tamara729, It will depend on how `read.csv()` treats the data as it is entered. There are some ways to look. The function `class(harvest_data$TotalDryWeight_g)` should return `numeric`, but would return `character` if the `"NA"` get in the way. Alternately, you could try `sum(harvest_data$TotalDryWeight_g)` expected to return `NA` without the `na.rm=T` argument.

**Comment by Tamara729** [comment]
@brymz Thank you, it came back as all numeric. 👍
